# Generated by Django 4.1 on 2023-07-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('shrimp', 'shrimp'), ('chicken', 'chicken'), ('pork', 'pork'), ('beef', 'beef'), ('tuna', 'tuna')], max_length=100)),
                ('bread', models.CharField(choices=[('white', 'white'), ('hati', 'hati'), ('parmesanOregano', 'parmesanOregano'), ('honeyOats', 'honeyOats')], max_length=100)),
                ('cheese', models.CharField(choices=[('mozzarella', 'mozzarella'), ('cheddar', 'cheddar'), ('americanCheese', 'americanCheese')], max_length=100)),
                ('tosting', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
