# Generated by Django 4.1 on 2023-07-24 14:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='vegetables',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lettuce', 'Lettuce'), ('Tomatoes', 'Tomatoes'), ('Cucumbers', 'Cucumbers'), ('Peppers', 'Peppers'), ('RedOnions', 'RedOnions'), ('Pickles', 'Pickles'), ('Olives', 'Olives'), ('Jalapenos', 'Jalapenos')], max_length=100, null=True),
        ),
    ]
