# Generated by Django 4.1 on 2023-07-24 15:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_sandwich_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='sauce',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ranch', 'Ranch'), ('SweetChilli', 'SweetChilli'), ('HoneyMustard', 'HoneyMustard'), ('SweetOnion', 'SweetOnion'), ('Mayonnaise', 'Mayonnaise'), ('SmokeBBQ', 'SmokeBBQ'), ('Horseradish', 'Horseradish')], max_length=100, null=True),
        ),
    ]
